language: node_js

node_js:
  - "lts/*"

cache: false

before_install:
  - sudo add-apt-repository -y ppa:libreoffice/ppa
  - sudo apt-get update
  - sudo apt-get -y install libreoffice
  - sudo apt-get -y install libreoffice-pdfimport

install:
  - "bin/installDeps.sh"
  - "export GIT_HASH=$(git rev-parse --verify --short HEAD)"
  

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

script:


after_script:
- ./cc-test-reporter after-build

script:
- "tests/frontend/travis/runner.sh"
- nyc --reporter=lcov npm run test

env:
  global:
  secure= "33DdjQ6wo8CvTyC5JHbhjOME//6zkVoCx28JzjdIWYGhcOyn/fk6yyVzvEdHRV0tbinO99pJzdlwZoYTBhicMFXT91nUYb7n0UIAVTxKOFevHEYppLpj6eYUk92ktKFOWSN0S5NMtf6+4GEqNNf9dnpGekXvKk86n/lbZSuOsBX9FIH5AiRiipwL4I5YlLJ+gri7KgEpk+zrSPaxcLVPtbWmlzvW8J5zv/zbmYSxSbFQZsWLN6PjFPbzX2UdBymfN+kw1QhALrt0xxDeutoPWwYQUb84cGbv5NVa6jGcyhTnCfFrorgRN+NQWmBR+gEEuNs/Ku6DiF+T9uAkhY//Es3XsUTFEUev4XCFwLoMUuotfIlHk5p6aBGDL8dyykli0ERkzGE0EUaAnynS+YNFb95eaEo2E/dsQtVGqFnjfXNgnzcwpwXDrt4yr0o6zkAEhlTgLP6fQMs0CSh7nft+XLeHzPUolBpX88ZlWoQQ67MdbD9gRlHP14H/Z0nCA+2npc5ggShkBqYUTGV+fkfTwozWIcbv4RZT8yT1NRZkaUTb5dM5O/ZbDfDrP+NUpqkh8POTShWYYDHEvdRc6PGDkXFOVI6E7hS8vF0xOhud2oJtPLtXyLGaaMS1czWPixDrcBQ4gRBgY8ekib6B1+R4fLLOzTsuQfwFpJ0gNraBYvc="

jobs:
  include:
    # we can only frontend tests from the ether/ organization and not from forks.
    # To request tests to be run ask a maintainer to fork your repo to ether/
    - if: fork = false
      name: "Test the Frontend"
      install:
        #FIXME
        - "sed 's/\"loglevel\": \"INFO\",/\"loglevel\": \"WARN\",/g' settings.json.template > settings.json"
        - "tests/frontend/travis/sauce_tunnel.sh"
        - "bin/installDeps.sh"
        - "export GIT_HASH=$(git rev-parse --verify --short HEAD)"
      script:
        - "tests/frontend/travis/runner.sh"
    - name: "Run the Backend tests"
      install:
        - "bin/installDeps.sh"
        - "cd src && npm install && cd -"
      script:
        - "tests/frontend/travis/runnerBackend.sh"
    - name: "Load test Etherpad"
      install:
        - "bin/installDeps.sh"
        - "cd src && npm install && cd -"
        - "npm install -g etherpad-load-test"
      script:
        - "tests/frontend/travis/runnerLoadTest.sh"
        
        

notifications:
 email:
  - geminientan@hotmail.com 
